const elements = [
  {
    number: 1,
    symbol: "H",
    viName: "Hiđro",
    enName: "Hydrogen",
    category: "phi kim",
    mass: "1.008",
    period: "1",
    state: "khí",
    x: 1,
    y: 1,
  },
  {
    number: 2,
    symbol: "He",
    viName: "Heli",
    enName: "Helium",
    category: "khí hiếm",
    mass: "4.0026",
    period: "1",
    state: "khí",
    x: 18,
    y: 1,
  },
  {
    number: 3,
    symbol: "Li",
    viName: "Liti",
    enName: "Lithium",
    category: "kim loại kiềm",
    mass: "6.94",
    period: "2",
    state: "rắn",
    x: 1,
    y: 2,
  },
  {
    number: 4,
    symbol: "Be",
    viName: "Beri",
    enName: "Beryllium",
    category: "kim loại kiềm thổ",
    mass: "9.0122",
    period: "2",
    state: "rắn",
    x: 2,
    y: 2,
  },
  {
    number: 5,
    symbol: "B",
    viName: "Bo",
    enName: "Boron",
    category: "á kim",
    mass: "10.81",
    period: "2",
    state: "rắn",
    x: 13,
    y: 2,
  },
  {
    number: 6,
    symbol: "C",
    viName: "Cacbon",
    enName: "Carbon",
    category: "phi kim",
    mass: "12.011",
    period: "2",
    state: "rắn",
    x: 14,
    y: 2,
  },
  {
    number: 7,
    symbol: "N",
    viName: "Nitơ",
    enName: "Nitrogen",
    category: "phi kim",
    mass: "14.007",
    period: "2",
    state: "khí",
    x: 15,
    y: 2,
  },
  {
    number: 8,
    symbol: "O",
    viName: "Oxi",
    enName: "Oxygen",
    category: "phi kim",
    mass: "15.999",
    period: "2",
    state: "khí",
    x: 16,
    y: 2,
  },
  {
    number: 9,
    symbol: "F",
    viName: "Flo",
    enName: "Fluorine",
    category: "halogen",
    mass: "18.998",
    period: "2",
    state: "khí",
    x: 17,
    y: 2,
  },
  {
    number: 10,
    symbol: "Ne",
    viName: "Neon",
    enName: "Neon",
    category: "khí hiếm",
    mass: "20.180",
    period: "2",
    state: "khí",
    x: 18,
    y: 2,
  },
  {
    number: 11,
    symbol: "Na",
    viName: "Natri",
    enName: "Sodium",
    category: "kim loại kiềm",
    mass: "22.990",
    period: "3",
    state: "rắn",
    x: 1,
    y: 3,
  },
  {
    number: 12,
    symbol: "Mg",
    viName: "Magiê",
    enName: "Magnesium",
    category: "kim loại kiềm thổ",
    mass: "24.305",
    period: "3",
    state: "rắn",
    x: 2,
    y: 3,
  },
  {
    number: 13,
    symbol: "Al",
    viName: "Nhôm",
    enName: "Aluminium",
    category: "kim loại hậu chuyển tiếp",
    mass: "26.982",
    period: "3",
    state: "rắn",
    x: 13,
    y: 3,
  },
  {
    number: 14,
    symbol: "Si",
    viName: "Silic",
    enName: "Silicon",
    category: "á kim",
    mass: "28.085",
    period: "3",
    state: "rắn",
    x: 14,
    y: 3,
  },
  {
    number: 15,
    symbol: "P",
    viName: "Photpho",
    enName: "Phosphorus",
    category: "phi kim",
    mass: "30.974",
    period: "3",
    state: "rắn",
    x: 15,
    y: 3,
  },
  {
    number: 16,
    symbol: "S",
    viName: "Lưu huỳnh",
    enName: "Sulfur",
    category: "phi kim",
    mass: "32.06",
    period: "3",
    state: "rắn",
    x: 16,
    y: 3,
  },
  {
    number: 17,
    symbol: "Cl",
    viName: "Clo",
    enName: "Chlorine",
    category: "halogen",
    mass: "35.45",
    period: "3",
    state: "khí",
    x: 17,
    y: 3,
  },
  {
    number: 18,
    symbol: "Ar",
    viName: "Argon",
    enName: "Argon",
    category: "khí hiếm",
    mass: "39.948",
    period: "3",
    state: "khí",
    x: 18,
    y: 3,
  },
  {
    number: 19,
    symbol: "K",
    viName: "Kali",
    enName: "Potassium",
    category: "kim loại kiềm",
    mass: "39.098",
    period: "4",
    state: "rắn",
    x: 1,
    y: 4,
  },
  {
    number: 20,
    symbol: "Ca",
    viName: "Canxi",
    enName: "Calcium",
    category: "kim loại kiềm thổ",
    mass: "40.078",
    period: "4",
    state: "rắn",
    x: 2,
    y: 4,
  },
  {
    number: 21,
    symbol: "Sc",
    viName: "Scandi",
    enName: "Scandium",
    category: "kim loại chuyển tiếp",
    mass: "44.956",
    period: "4",
    state: "rắn",
    x: 3,
    y: 4,
  },
  {
    number: 22,
    symbol: "Ti",
    viName: "Titan",
    enName: "Titanium",
    category: "kim loại chuyển tiếp",
    mass: "47.867",
    period: "4",
    state: "rắn",
    x: 4,
    y: 4,
  },
  {
    number: 23,
    symbol: "V",
    viName: "Vanadi",
    enName: "Vanadium",
    category: "kim loại chuyển tiếp",
    mass: "50.942",
    period: "4",
    state: "rắn",
    x: 5,
    y: 4,
  },
  {
    number: 24,
    symbol: "Cr",
    viName: "Crom",
    enName: "Chromium",
    category: "kim loại chuyển tiếp",
    mass: "51.996",
    period: "4",
    state: "rắn",
    x: 6,
    y: 4,
  },
  {
    number: 25,
    symbol: "Mn",
    viName: "Mangan",
    enName: "Manganese",
    category: "kim loại chuyển tiếp",
    mass: "54.938",
    period: "4",
    state: "rắn",
    x: 7,
    y: 4,
  },
  {
    number: 26,
    symbol: "Fe",
    viName: "Sắt",
    enName: "Iron",
    category: "kim loại chuyển tiếp",
    mass: "55.845",
    period: "4",
    state: "rắn",
    x: 8,
    y: 4,
  },
  {
    number: 27,
    symbol: "Co",
    viName: "Coban",
    enName: "Cobalt",
    category: "kim loại chuyển tiếp",
    mass: "58.933",
    period: "4",
    state: "rắn",
    x: 9,
    y: 4,
  },
  {
    number: 28,
    symbol: "Ni",
    viName: "Niken",
    enName: "Nickel",
    category: "kim loại chuyển tiếp",
    mass: "58.693",
    period: "4",
    state: "rắn",
    x: 10,
    y: 4,
  },
  {
    number: 29,
    symbol: "Cu",
    viName: "Đồng",
    enName: "Copper",
    category: "kim loại chuyển tiếp",
    mass: "63.546",
    period: "4",
    state: "rắn",
    x: 11,
    y: 4,
  },
  {
    number: 30,
    symbol: "Zn",
    viName: "Kẽm",
    enName: "Zinc",
    category: "kim loại chuyển tiếp",
    mass: "65.38",
    period: "4",
    state: "rắn",
    x: 12,
    y: 4,
  },
  {
    number: 31,
    symbol: "Ga",
    viName: "Gali",
    enName: "Gallium",
    category: "kim loại hậu chuyển tiếp",
    mass: "69.723",
    period: "4",
    state: "rắn",
    x: 13,
    y: 4,
  },
  {
    number: 32,
    symbol: "Ge",
    viName: "Gecmani",
    enName: "Germanium",
    category: "á kim",
    mass: "72.630",
    period: "4",
    state: "rắn",
    x: 14,
    y: 4,
  },
  {
    number: 33,
    symbol: "As",
    viName: "Asen",
    enName: "Arsenic",
    category: "á kim",
    mass: "74.922",
    period: "4",
    state: "rắn",
    x: 15,
    y: 4,
  },
  {
    number: 34,
    symbol: "Se",
    viName: "Selen",
    enName: "Selenium",
    category: "phi kim",
    mass: "78.971",
    period: "4",
    state: "rắn",
    x: 16,
    y: 4,
  },
  {
    number: 35,
    symbol: "Br",
    viName: "Brom",
    enName: "Bromine",
    category: "halogen",
    mass: "79.904",
    period: "4",
    state: "lỏng",
    x: 17,
    y: 4,
  },
  {
    number: 36,
    symbol: "Kr",
    viName: "Krypton",
    enName: "Krypton",
    category: "khí hiếm",
    mass: "83.798",
    period: "4",
    state: "khí",
    x: 18,
    y: 4,
  },
  {
    number: 37,
    symbol: "Rb",
    viName: "Rubidi",
    enName: "Rubidium",
    category: "kim loại kiềm",
    mass: "85.468",
    period: "5",
    state: "rắn",
    x: 1,
    y: 5,
  },
  {
    number: 38,
    symbol: "Sr",
    viName: "Stronti",
    enName: "Strontium",
    category: "kim loại kiềm thổ",
    mass: "87.62",
    period: "5",
    state: "rắn",
    x: 2,
    y: 5,
  },
  {
    number: 39,
    symbol: "Y",
    viName: "Ytri",
    enName: "Yttrium",
    category: "kim loại chuyển tiếp",
    mass: "88.906",
    period: "5",
    state: "rắn",
    x: 3,
    y: 5,
  },
  {
    number: 40,
    symbol: "Zr",
    viName: "Zirconi",
    enName: "Zirconium",
    category: "kim loại chuyển tiếp",
    mass: "91.224",
    period: "5",
    state: "rắn",
    x: 4,
    y: 5,
  },
  {
    number: 41,
    symbol: "Nb",
    viName: "Niobi",
    enName: "Niobium",
    category: "kim loại chuyển tiếp",
    mass: "92.906",
    period: "5",
    state: "rắn",
    x: 5,
    y: 5,
  },
  {
    number: 42,
    symbol: "Mo",
    viName: "Molypden",
    enName: "Molybdenum",
    category: "kim loại chuyển tiếp",
    mass: "95.95",
    period: "5",
    state: "rắn",
    x: 6,
    y: 5,
  },
  {
    number: 43,
    symbol: "Tc",
    viName: "Techneti",
    enName: "Technetium",
    category: "kim loại chuyển tiếp",
    mass: "98",
    period: "5",
    state: "rắn (phóng xạ)",
    x: 7,
    y: 5,
  },
  {
    number: 44,
    symbol: "Ru",
    viName: "Rutheni",
    enName: "Ruthenium",
    category: "kim loại chuyển tiếp",
    mass: "101.07",
    period: "5",
    state: "rắn",
    x: 8,
    y: 5,
  },
  {
    number: 45,
    symbol: "Rh",
    viName: "Rodi",
    enName: "Rhodium",
    category: "kim loại chuyển tiếp",
    mass: "102.91",
    period: "5",
    state: "rắn",
    x: 9,
    y: 5,
  },
  {
    number: 46,
    symbol: "Pd",
    viName: "Paladi",
    enName: "Palladium",
    category: "kim loại chuyển tiếp",
    mass: "106.42",
    period: "5",
    state: "rắn",
    x: 10,
    y: 5,
  },
  {
    number: 47,
    symbol: "Ag",
    viName: "Bạc",
    enName: "Silver",
    category: "kim loại chuyển tiếp",
    mass: "107.87",
    period: "5",
    state: "rắn",
    x: 11,
    y: 5,
  },
  {
    number: 48,
    symbol: "Cd",
    viName: "Cadimi",
    enName: "Cadmium",
    category: "kim loại chuyển tiếp",
    mass: "112.41",
    period: "5",
    state: "rắn",
    x: 12,
    y: 5,
  },
  {
    number: 49,
    symbol: "In",
    viName: "Indi",
    enName: "Indium",
    category: "kim loại hậu chuyển tiếp",
    mass: "114.82",
    period: "5",
    state: "rắn",
    x: 13,
    y: 5,
  },
  {
    number: 50,
    symbol: "Sn",
    viName: "Thiếc",
    enName: "Tin",
    category: "kim loại hậu chuyển tiếp",
    mass: "118.71",
    period: "5",
    state: "rắn",
    x: 14,
    y: 5,
  },
  {
    number: 51,
    symbol: "Sb",
    viName: "Antimon",
    enName: "Antimony",
    category: "á kim",
    mass: "121.76",
    period: "5",
    state: "rắn",
    x: 15,
    y: 5,
  },
  {
    number: 52,
    symbol: "Te",
    viName: "Telua",
    enName: "Tellurium",
    category: "á kim",
    mass: "127.60",
    period: "5",
    state: "rắn",
    x: 16,
    y: 5,
  },
  {
    number: 53,
    symbol: "I",
    viName: "Iốt",
    enName: "Iodine",
    category: "halogen",
    mass: "126.90",
    period: "5",
    state: "rắn",
    x: 17,
    y: 5,
  },
  {
    number: 54,
    symbol: "Xe",
    viName: "Xenon",
    enName: "Xenon",
    category: "khí hiếm",
    mass: "131.29",
    period: "5",
    state: "khí",
    x: 18,
    y: 5,
  },
  {
    number: 55,
    symbol: "Cs",
    viName: "Xesi",
    enName: "Cesium",
    category: "kim loại kiềm",
    mass: "132.91",
    period: "6",
    state: "rắn",
    x: 1,
    y: 6,
  },
  {
    number: 56,
    symbol: "Ba",
    viName: "Bari",
    enName: "Barium",
    category: "kim loại kiềm thổ",
    mass: "137.33",
    period: "6",
    state: "rắn",
    x: 2,
    y: 6,
  },
  {
    number: 57,
    symbol: "La",
    viName: "Lantan",
    enName: "Lanthanum",
    category: "lantanide",
    mass: "138.91",
    period: "6",
    state: "rắn",
    x: 3,
    y: 9,
  },
  {
    number: 58,
    symbol: "Ce",
    viName: "Xeri",
    enName: "Cerium",
    category: "lantanide",
    mass: "140.12",
    period: "6",
    state: "rắn",
    x: 4,
    y: 9,
  },
  {
    number: 59,
    symbol: "Pr",
    viName: "Praseodymi",
    enName: "Praseodymium",
    category: "lantanide",
    mass: "140.91",
    period: "6",
    state: "rắn",
    x: 5,
    y: 9,
  },
  {
    number: 60,
    symbol: "Nd",
    viName: "Neodymi",
    enName: "Neodymium",
    category: "lantanide",
    mass: "144.24",
    period: "6",
    state: "rắn",
    x: 6,
    y: 9,
  },
  {
    number: 61,
    symbol: "Pm",
    viName: "Promethi",
    enName: "Promethium",
    category: "lantanide",
    mass: "145",
    period: "6",
    state: "rắn (phóng xạ)",
    x: 7,
    y: 9,
  },
  {
    number: 62,
    symbol: "Sm",
    viName: "Samari",
    enName: "Samarium",
    category: "lantanide",
    mass: "150.36",
    period: "6",
    state: "rắn",
    x: 8,
    y: 9,
  },
  {
    number: 63,
    symbol: "Eu",
    viName: "Europi",
    enName: "Europium",
    category: "lantanide",
    mass: "151.96",
    period: "6",
    state: "rắn",
    x: 9,
    y: 9,
  },
  {
    number: 64,
    symbol: "Gd",
    viName: "Gadolini",
    enName: "Gadolinium",
    category: "lantanide",
    mass: "157.25",
    period: "6",
    state: "rắn",
    x: 10,
    y: 9,
  },
  {
    number: 65,
    symbol: "Tb",
    viName: "Terbi",
    enName: "Terbium",
    category: "lantanide",
    mass: "158.93",
    period: "6",
    state: "rắn",
    x: 11,
    y: 9,
  },
  {
    number: 66,
    symbol: "Dy",
    viName: "Disprosi",
    enName: "Dysprosium",
    category: "lantanide",
    mass: "162.50",
    period: "6",
    state: "rắn",
    x: 12,
    y: 9,
  },
  {
    number: 67,
    symbol: "Ho",
    viName: "Holmi",
    enName: "Holmium",
    category: "lantanide",
    mass: "164.93",
    period: "6",
    state: "rắn",
    x: 13,
    y: 9,
  },
  {
    number: 68,
    symbol: "Er",
    viName: "Erbi",
    enName: "Erbium",
    category: "lantanide",
    mass: "167.26",
    period: "6",
    state: "rắn",
    x: 14,
    y: 9,
  },
  {
    number: 69,
    symbol: "Tm",
    viName: "Thuli",
    enName: "Thulium",
    category: "lantanide",
    mass: "168.93",
    period: "6",
    state: "rắn",
    x: 15,
    y: 9,
  },
  {
    number: 70,
    symbol: "Yb",
    viName: "Yttebi",
    enName: "Ytterbium",
    category: "lantanide",
    mass: "173.05",
    period: "6",
    state: "rắn",
    x: 16,
    y: 9,
  },
  {
    number: 71,
    symbol: "Lu",
    viName: "Luteti",
    enName: "Lutetium",
    category: "lantanide",
    mass: "174.97",
    period: "6",
    state: "rắn",
    x: 17,
    y: 9,
  },
  {
    number: 72,
    symbol: "Hf",
    viName: "Hafni",
    enName: "Hafnium",
    category: "kim loại chuyển tiếp",
    mass: "178.49",
    period: "6",
    state: "rắn",
    x: 4,
    y: 6,
  },
  {
    number: 73,
    symbol: "Ta",
    viName: "Tantali",
    enName: "Tantalum",
    category: "kim loại chuyển tiếp",
    mass: "180.95",
    period: "6",
    state: "rắn",
    x: 5,
    y: 6,
  },
  {
    number: 74,
    symbol: "W",
    viName: "Vonfram",
    enName: "Tungsten",
    category: "kim loại chuyển tiếp",
    mass: "183.84",
    period: "6",
    state: "rắn",
    x: 6,
    y: 6,
  },
  {
    number: 75,
    symbol: "Re",
    viName: "Rheni",
    enName: "Rhenium",
    category: "kim loại chuyển tiếp",
    mass: "186.21",
    period: "6",
    state: "rắn",
    x: 7,
    y: 6,
  },
  {
    number: 76,
    symbol: "Os",
    viName: "Osmium",
    enName: "Osmium",
    category: "kim loại chuyển tiếp",
    mass: "190.23",
    period: "6",
    state: "rắn",
    x: 8,
    y: 6,
  },
  {
    number: 77,
    symbol: "Ir",
    viName: "Iridi",
    enName: "Iridium",
    category: "kim loại chuyển tiếp",
    mass: "192.22",
    period: "6",
    state: "rắn",
    x: 9,
    y: 6,
  },
  {
    number: 78,
    symbol: "Pt",
    viName: "Platin",
    enName: "Platinum",
    category: "kim loại chuyển tiếp",
    mass: "195.08",
    period: "6",
    state: "rắn",
    x: 10,
    y: 6,
  },
  {
    number: 79,
    symbol: "Au",
    viName: "Vàng",
    enName: "Gold",
    category: "kim loại chuyển tiếp",
    mass: "196.97",
    period: "6",
    state: "rắn",
    x: 11,
    y: 6,
  },
  {
    number: 80,
    symbol: "Hg",
    viName: "Thủy ngân",
    enName: "Mercury",
    category: "kim loại chuyển tiếp",
    mass: "200.59",
    period: "6",
    state: "lỏng",
    x: 12,
    y: 6,
  },
  {
    number: 81,
    symbol: "Tl",
    viName: "Thali",
    enName: "Thallium",
    category: "kim loại hậu chuyển tiếp",
    mass: "204.38",
    period: "6",
    state: "rắn",
    x: 13,
    y: 6,
  },
  {
    number: 82,
    symbol: "Pb",
    viName: "Chì",
    enName: "Lead",
    category: "kim loại hậu chuyển tiếp",
    mass: "207.2",
    period: "6",
    state: "rắn",
    x: 14,
    y: 6,
  },
  {
    number: 83,
    symbol: "Bi",
    viName: "Bitmut",
    enName: "Bismuth",
    category: "kim loại hậu chuyển tiếp",
    mass: "208.98",
    period: "6",
    state: "rắn",
    x: 15,
    y: 6,
  },
  {
    number: 84,
    symbol: "Po",
    viName: "Poloni",
    enName: "Polonium",
    category: "á kim",
    mass: "209",
    period: "6",
    state: "rắn (phóng xạ)",
    x: 16,
    y: 6,
  },
  {
    number: 85,
    symbol: "At",
    viName: "Astatin",
    enName: "Astatine",
    category: "halogen",
    mass: "210",
    period: "6",
    state: "rắn (phóng xạ)",
    x: 17,
    y: 6,
  },
  {
    number: 86,
    symbol: "Rn",
    viName: "Radon",
    enName: "Radon",
    category: "khí hiếm",
    mass: "222",
    period: "6",
    state: "khí (phóng xạ)",
    x: 18,
    y: 6,
  },
  {
    number: 87,
    symbol: "Fr",
    viName: "Francium",
    enName: "Francium",
    category: "kim loại kiềm",
    mass: "223",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 1,
    y: 7,
  },
  {
    number: 88,
    symbol: "Ra",
    viName: "Radi",
    enName: "Radium",
    category: "kim loại kiềm thổ",
    mass: "226",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 2,
    y: 7,
  },
  {
    number: 89,
    symbol: "Ac",
    viName: "Actini",
    enName: "Actinium",
    category: "actinide",
    mass: "227",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 3,
    y: 10,
  },
  {
    number: 90,
    symbol: "Th",
    viName: "Thori",
    enName: "Thorium",
    category: "actinide",
    mass: "232.04",
    period: "7",
    state: "rắn",
    x: 4,
    y: 10,
  },
  {
    number: 91,
    symbol: "Pa",
    viName: "Protactini",
    enName: "Protactinium",
    category: "actinide",
    mass: "231.04",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 5,
    y: 10,
  },
  {
    number: 92,
    symbol: "U",
    viName: "Uran",
    enName: "Uranium",
    category: "actinide",
    mass: "238.03",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 6,
    y: 10,
  },
  {
    number: 93,
    symbol: "Np",
    viName: "Neptuni",
    enName: "Neptunium",
    category: "actinide",
    mass: "237",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 7,
    y: 10,
  },
  {
    number: 94,
    symbol: "Pu",
    viName: "Plutoni",
    enName: "Plutonium",
    category: "actinide",
    mass: "244",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 8,
    y: 10,
  },
  {
    number: 95,
    symbol: "Am",
    viName: "Americi",
    enName: "Americium",
    category: "actinide",
    mass: "243",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 9,
    y: 10,
  },
  {
    number: 96,
    symbol: "Cm",
    viName: "Curium",
    enName: "Curium",
    category: "actinide",
    mass: "247",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 10,
    y: 10,
  },
  {
    number: 97,
    symbol: "Bk",
    viName: "Berkeli",
    enName: "Berkelium",
    category: "actinide",
    mass: "247",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 11,
    y: 10,
  },
  {
    number: 98,
    symbol: "Cf",
    viName: "Californi",
    enName: "Californium",
    category: "actinide",
    mass: "251",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 12,
    y: 10,
  },
  {
    number: 99,
    symbol: "Es",
    viName: "Einsteini",
    enName: "Einsteinium",
    category: "actinide",
    mass: "252",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 13,
    y: 10,
  },
  {
    number: 100,
    symbol: "Fm",
    viName: "Fermi",
    enName: "Fermium",
    category: "actinide",
    mass: "257",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 14,
    y: 10,
  },
  {
    number: 101,
    symbol: "Md",
    viName: "Mendelevi",
    enName: "Mendelevium",
    category: "actinide",
    mass: "258",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 15,
    y: 10,
  },
  {
    number: 102,
    symbol: "No",
    viName: "Nobeli",
    enName: "Nobelium",
    category: "actinide",
    mass: "259",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 16,
    y: 10,
  },
  {
    number: 103,
    symbol: "Lr",
    viName: "Lawrenci",
    enName: "Lawrencium",
    category: "actinide",
    mass: "266",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 17,
    y: 10,
  },
  {
    number: 104,
    symbol: "Rf",
    viName: "Rutherfordi",
    enName: "Rutherfordium",
    category: "kim loại chuyển tiếp",
    mass: "267",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 4,
    y: 7,
  },
  {
    number: 105,
    symbol: "Db",
    viName: "Dubni",
    enName: "Dubnium",
    category: "kim loại chuyển tiếp",
    mass: "268",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 5,
    y: 7,
  },
  {
    number: 106,
    symbol: "Sg",
    viName: "Seaborgi",
    enName: "Seaborgium",
    category: "kim loại chuyển tiếp",
    mass: "269",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 6,
    y: 7,
  },
  {
    number: 107,
    symbol: "Bh",
    viName: "Bohr",
    enName: "Bohrium",
    category: "kim loại chuyển tiếp",
    mass: "270",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 7,
    y: 7,
  },
  {
    number: 108,
    symbol: "Hs",
    viName: "Hassi",
    enName: "Hassium",
    category: "kim loại chuyển tiếp",
    mass: "269",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 8,
    y: 7,
  },
  {
    number: 109,
    symbol: "Mt",
    viName: "Meitneri",
    enName: "Meitnerium",
    category: "kim loại chuyển tiếp",
    mass: "278",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 9,
    y: 7,
  },
  {
    number: 110,
    symbol: "Ds",
    viName: "Darmstadti",
    enName: "Darmstadtium",
    category: "kim loại chuyển tiếp",
    mass: "281",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 10,
    y: 7,
  },
  {
    number: 111,
    symbol: "Rg",
    viName: "Roentgeni",
    enName: "Roentgenium",
    category: "kim loại chuyển tiếp",
    mass: "282",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 11,
    y: 7,
  },
  {
    number: 112,
    symbol: "Cn",
    viName: "Copernici",
    enName: "Copernicium",
    category: "kim loại chuyển tiếp",
    mass: "285",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 12,
    y: 7,
  },
  {
    number: 113,
    symbol: "Nh",
    viName: "Nihoni",
    enName: "Nihonium",
    category: "kim loại hậu chuyển tiếp",
    mass: "286",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 13,
    y: 7,
  },
  {
    number: 114,
    symbol: "Fl",
    viName: "Flerovi",
    enName: "Flerovium",
    category: "kim loại hậu chuyển tiếp",
    mass: "289",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 14,
    y: 7,
  },
  {
    number: 115,
    symbol: "Mc",
    viName: "Moscovi",
    enName: "Moscovium",
    category: "kim loại hậu chuyển tiếp",
    mass: "290",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 15,
    y: 7,
  },
  {
    number: 116,
    symbol: "Lv",
    viName: "Livermori",
    enName: "Livermorium",
    category: "kim loại hậu chuyển tiếp",
    mass: "293",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 16,
    y: 7,
  },
  {
    number: 117,
    symbol: "Ts",
    viName: "Tennessin",
    enName: "Tennessine",
    category: "halogen",
    mass: "294",
    period: "7",
    state: "rắn (phóng xạ)",
    x: 17,
    y: 7,
  },
  {
    number: 118,
    symbol: "Og",
    viName: "Oganeson",
    enName: "Oganesson",
    category: "khí hiếm",
    mass: "294",
    period: "7",
    state: "khí (phóng xạ, theo dự đoán)",
    x: 18,
    y: 7,
  },
];

export default elements;
